(function() {var implementors = {
"hyperion_arch_x86_64":[["impl&lt;T: <a class=\"trait\" href=\"hyperion_arch_x86_64/stack/trait.StackType.html\" title=\"trait hyperion_arch_x86_64::stack::StackType\">StackType</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_arch_x86_64/stack/struct.Stacks.html\" title=\"struct hyperion_arch_x86_64::stack::Stacks\">Stacks</a>&lt;T&gt;"],["impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_arch_x86_64/stack/struct.Stack.html\" title=\"struct hyperion_arch_x86_64::stack::Stack\">Stack</a>&lt;T&gt;"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_arch_x86_64/syscall/struct.SyscallRegs.html\" title=\"struct hyperion_arch_x86_64::syscall::SyscallRegs\">SyscallRegs</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_arch_x86_64/cpu/tss/struct.Tss.html\" title=\"struct hyperion_arch_x86_64::cpu::tss::Tss\">Tss</a>"]],
"hyperion_bitmap":[["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_bitmap/struct.Bitmap.html\" title=\"struct hyperion_bitmap::Bitmap\">Bitmap</a>&lt;'a&gt;"]],
"hyperion_boot":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_boot/args/struct.Arguments.html\" title=\"struct hyperion_boot::args::Arguments\">Arguments</a>"]],
"hyperion_color":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_color/struct.Color.html\" title=\"struct hyperion_color::Color\">Color</a>"]],
"hyperion_driver_rtc":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_driver_rtc/struct.Rtc.html\" title=\"struct hyperion_driver_rtc::Rtc\">Rtc</a>"]],
"hyperion_escape":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_escape/encode/struct.EncodedPart.html\" title=\"struct hyperion_escape::encode::EncodedPart\">EncodedPart</a>&lt;'static, <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/core/primitive.unit.html\">()</a>&gt;"]],
"hyperion_framebuffer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_framebuffer/framebuffer/struct.FramebufferInfo.html\" title=\"struct hyperion_framebuffer::framebuffer::FramebufferInfo\">FramebufferInfo</a>"]],
"hyperion_futures":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_futures/keyboard/struct.KeyboardEvents.html\" title=\"struct hyperion_futures::keyboard::KeyboardEvents\">KeyboardEvents</a>"]],
"hyperion_int_safe_lazy":[["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_int_safe_lazy/struct.IntSafeLazy.html\" title=\"struct hyperion_int_safe_lazy::IntSafeLazy\">IntSafeLazy</a>&lt;T, <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/core/primitive.fn.html\">fn</a>() -&gt; T&gt;"]],
"hyperion_interrupts":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"hyperion_interrupts/enum.IntController.html\" title=\"enum hyperion_interrupts::IntController\">IntController</a>"]],
"hyperion_kshell":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_kshell/term/struct.Term.html\" title=\"struct hyperion_kshell::term::Term\">Term</a>"]],
"hyperion_log":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"hyperion_log/enum.LogLevel.html\" title=\"enum hyperion_log::LogLevel\">LogLevel</a>"]],
"hyperion_scheduler":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_scheduler/task/struct.PageAllocs.html\" title=\"struct hyperion_scheduler::task::PageAllocs\">PageAllocs</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"type\" href=\"hyperion_scheduler/ipc/pipe/type.Pipe.html\" title=\"type hyperion_scheduler::ipc::pipe::Pipe\">Pipe</a>"]],
"hyperion_slab_alloc":[["impl&lt;P, Lock&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"hyperion_slab_alloc/struct.SlabAllocator.html\" title=\"struct hyperion_slab_alloc::SlabAllocator\">SlabAllocator</a>&lt;P, Lock&gt;<div class=\"where\">where\n    Lock: RawMutex,</div>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()