[package]
name = "hyperion-scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
arcstr.workspace = true
crossbeam.workspace = true
spin.workspace = true
x86_64.workspace = true

hyperion-arch.path = "../arch"
hyperion-futures.path = "../futures"
hyperion-mem.path = "../mem"
hyperion-log.path = "../log"
hyperion-sync.path = "../sync"
hyperion-syscall.path = "../syscall"

[lints]
workspace = true
