(function() {var implementors = {
"hyperion_cpu_id":[["impl&lt;T: 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_cpu_id/struct.Tls.html\" title=\"struct hyperion_cpu_id::Tls\">Tls</a>&lt;T&gt;"]],
"hyperion_defer":[["impl&lt;F: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.FnOnce.html\" title=\"trait core::ops::function::FnOnce\">FnOnce</a>() -&gt; T, T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_defer/struct.DeferInit.html\" title=\"struct hyperion_defer::DeferInit\">DeferInit</a>&lt;F, T&gt;"]],
"hyperion_driver_acpi":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_driver_acpi/hpet/struct.TimerNHandle.html\" title=\"struct hyperion_driver_acpi::hpet::TimerNHandle\">TimerNHandle</a>&lt;'_&gt;"],["impl&lt;T: 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_driver_acpi/apic/struct.ApicTls.html\" title=\"struct hyperion_driver_acpi::apic::ApicTls\">ApicTls</a>&lt;T&gt;"]],
"hyperion_framebuffer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_framebuffer/framebuffer/struct.Framebuffer.html\" title=\"struct hyperion_framebuffer::framebuffer::Framebuffer\">Framebuffer</a>"]],
"hyperion_futures":[["impl&lt;'a, T: ?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_futures/lock/struct.MutexGuard.html\" title=\"struct hyperion_futures::lock::MutexGuard\">MutexGuard</a>&lt;'a, T&gt;"]],
"hyperion_ring":[["impl&lt;T, const N: <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/core/primitive.usize.html\">usize</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_ring/struct.Static.html\" title=\"struct hyperion_ring::Static\">Static</a>&lt;T, N&gt;"]],
"hyperion_scheduler":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_scheduler/task/struct.Task.html\" title=\"struct hyperion_scheduler::task::Task\">Task</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_scheduler/task/struct.TaskInner.html\" title=\"struct hyperion_scheduler::task::TaskInner\">TaskInner</a>"],["impl&lt;T, F: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.FnOnce.html\" title=\"trait core::ops::function::FnOnce\">FnOnce</a>() -&gt; T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_scheduler/lock/struct.Lazy.html\" title=\"struct hyperion_scheduler::lock::Lazy\">Lazy</a>&lt;T, F&gt;"]],
"hyperion_slab_alloc":[["impl&lt;P, Lock&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_slab_alloc/struct.SlabAllocator.html\" title=\"struct hyperion_slab_alloc::SlabAllocator\">SlabAllocator</a>&lt;P, Lock&gt;"]],
"hyperion_static_str":[["impl&lt;const SIZE: <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/core/primitive.usize.html\">usize</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_static_str/struct.StaticStr.html\" title=\"struct hyperion_static_str::StaticStr\">StaticStr</a>&lt;SIZE&gt;"]],
"hyperion_vfs":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"hyperion_vfs/path/struct.PathBuf.html\" title=\"struct hyperion_vfs::path::PathBuf\">PathBuf</a>"]],
"libstd":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"libstd/io/struct.StdoutLock.html\" title=\"struct libstd::io::StdoutLock\">StdoutLock</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"libstd/io/struct.StderrLock.html\" title=\"struct libstd::io::StderrLock\">StderrLock</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"libstd/io/struct.StdinLock.html\" title=\"struct libstd::io::StdinLock\">StdinLock</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()